/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMyScheduleRouteImport } from './routes/_app/my-schedule'
import { Route as AppMyWeekRouteImport } from './routes/_app/my-week'
import { Route as AppPlannerRouteImport } from './routes/_app/planner'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMyScheduleRoute = AppMyScheduleRouteImport.update({
  id: '/my-schedule',
  path: '/my-schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppMyWeekRoute = AppMyWeekRouteImport.update({
  id: '/my-week',
  path: '/my-week',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/my-schedule': typeof AppMyScheduleRoute
  '/my-week': typeof AppMyWeekRoute
  '/planner': typeof AppPlannerRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/my-schedule': typeof AppMyScheduleRoute
  '/my-week': typeof AppMyWeekRoute
  '/planner': typeof AppPlannerRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/my-schedule': typeof AppMyScheduleRoute
  '/_app/my-week': typeof AppMyWeekRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/my-schedule' | '/my-week' | '/planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/my-schedule' | '/my-week' | '/planner' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/my-schedule'
    | '/_app/my-week'
    | '/_app/planner'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-schedule': {
      id: '/_app/my-schedule'
      path: '/my-schedule'
      fullPath: '/my-schedule'
      preLoaderRoute: typeof AppMyScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-week': {
      id: '/_app/my-week'
      path: '/my-week'
      fullPath: '/my-week'
      preLoaderRoute: typeof AppMyWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMyScheduleRoute: typeof AppMyScheduleRoute
  AppMyWeekRoute: typeof AppMyWeekRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMyScheduleRoute: AppMyScheduleRoute,
  AppMyWeekRoute: AppMyWeekRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
